### ISSUE TITLE
Tesseract not working 

### ISSUE THREAD

**Issue by jithurjacob** [nomuna/opencv_tesseract#1]
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    api = tesseract.TessBaseAPI()
AttributeError: 'module' object has no attribute 'TessBaseAPI'

I'm getting this error

**Comment by nomuna** [comment]
1. You mean line 18 in ocr_on_cropped.py?
2. Are you sure you have installed the python tesserat api from the url I have provided in the 
readme file? I have the version python_tesseract-0.9 installed.

Specifically it was the python-tesseract_0.9-0.5ubuntu_trusty_amd64.deb file I downloaded from the
bitbucket site in the readme.

**Comment by jithurjacob** [comment]
I've got it some how working. I'm on Windows.

**Comment by nomuna** [comment]
Glad to hear that. :D

**Comment by wangchuan** [comment]
@jithurjacob , I have encountered the same problem. How did you fix it?

**Comment by jenish08** [comment]
I have encountered the same problem. How did you fix it?
